
create table sys_company (
    id varchar(64) PRIMARY KEY,
    name varchar(255) DEFAULT NULL,
    start_date DATE DEFAULT NULL,
    market_cap DECIMAL(18,8) DEFAULT NULL,
    unified_code varchar(255) DEFAULT NULL
);

create table sys_auto_user (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    first_name varchar(64),
    last_name varchar(64),
    deleted INTEGER DEFAULT NULL
);
